build(docker): #57 Build from recent image
RMI-PACTA/workflow.prepare.pacta.indices pull request #59
Opened 2024-02-26 16:14 UTC by AlexAxthelm

Build from a recent image from the public registry for `workflow.transition.monitor`. While these images don't include the pacta-data needed to prepare indices, the current README instructions include a requirement to externally mount PACTA-data.

Closes: #57

2024-02-26 16:34 UTC, AlexAxthelm commented
long-term goal: use explicit pinning on SHA for stability

```
FROM ghcr.io/rmi-pacta/workflow.transition.monitor@sha256:4cb557ea3155f53a16253e85ed5a7986076c58eee335d685dd30183a038ef5b7
```

2024-02-26 16:40 UTC, cjyetman commented
maybe should update the README along with this?
https://github.com/RMI-PACTA/workflow.prepare.pacta.indices/blob/cac36eeab6a570de64889c7390fe0a65b00cfcb7/README.md?plain=1#L15-L20

2024-02-26 16:59 UTC, jdhoffa requested changes
Agreed, please update `README` accordingly

2024-02-26 17:13 UTC, cjyetman commented
verified that this works once #62 is included

2024-02-26 17:46 UTC, cjyetman commented on README.md
> +Although the image is public, pullang public images ffrom GHCR requires authentication.
```suggestion
Although the image is public, pulling public images from GHCR requires authentication.
```

2024-02-26 17:48 UTC, cjyetman requested changes
see minor spelling suggestions

2024-02-26 18:12 UTC, cjyetman approved these changes

2024-02-26 21:28 UTC, AlexAxthelm commented
Note, we can't get around the install requirement entirely, since `pacta.data.scraping` needs to be installed, but here's the relevant output from a build I just started
```
#8 55.06
#8 55.11 → Will install 14 packages.
#8 55.26 → All 15 packages (0 B) are cached.
#8 55.28 + askpass               1.2.0
#8 55.28 + curl                  5.1.0       + ✔ libcurl4-openssl-dev, ✔ libssl-dev
#8 55.28 + httr                  1.4.7
#8 55.28 + httr2                 0.2.3
#8 55.28 + logger                0.2.2
#8 55.28 + lubridate             1.9.3
#8 55.28 + openssl               2.1.1       + ✔ libssl-dev
#8 55.28 + pacta.data.scraping   0.1.0.9000 [bld][cmp] (GitHub: 91302af)
#8 55.28 + rvest                 1.0.3
#8 55.28 + selectr               0.4-2
#8 55.28 + sys                   3.4.2
#8 55.28 + timechange            0.2.0
#8 55.28 + V8                    4.4.0       + ✖ libnode-dev
#8 55.28 + xml2                  1.3.5       + ✖ libxml2-dev
#8 55.35 → Will install 2 system packages:
#8 55.37 + libnode-dev  - V8
#8 55.37 + libxml2-dev  - xml2
```

and we can see that. it's not trying to reinstall any of the other pacta packages.

2024-02-26 21:29 UTC, AlexAxthelm commented
Would it be prudent to fail the build if (pacta) dependencies are out of date?

2024-02-26 21:32 UTC, cjyetman commented
pacta.data.scraping is fine to install, it's just the packages already in the TM image that we should avoid overwriting.

2024-02-26 21:38 UTC, cjyetman commented on Dockerfile
>  # https://packagemanager.rstudio.com/cran/__linux__/jammy/2023-03-31+MbiAEzHt
remove these comments if they're not being used

2024-02-27 11:37 UTC, cjyetman approved these changes

2024-02-27 12:12 UTC, jdhoffa approved these changes
I am trusting @cjyetman's review and rubber stamping.
I did not review this myself.

2024-02-27 12:19 UTC, merged